apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: fhaa
  name: fhaa-buildconfig
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/junyjoy/Fhaha.git'
    contextDir: /
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python-311:1-8.1686736783'
