kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"fhaa-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"fhaa-app\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '7197341'
  name: fhaa-app
  generation: 7
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      fieldsType: FieldsV1
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-20T01:25:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"fhaa-app"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-20T01:25:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: fhaa
  labels:
    app: fhaa-app
    app.kubernetes.io/component: fhaa-app
    app.kubernetes.io/instance: fhaa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: fhaa-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: fhaa-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: fhaa-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/fhaa/fhaa-app@sha256:3c43969a1f41300144f59505c8c69fc8cf5ee5eda5a229bc13dce0b30ef42eb7
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Seoul
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
