apiVersion: v1
kind: Service
metadata:
  name: fhaa-svc
  namespace: fhaa
  labels:
    app: fhaa-app
spec:
  selector:
    deployment: fhaa-app
  ports:
    - protocol: 8080-tcp
      port: 80
      targetPort: 9376
