apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fhaa-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fhaa-app
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 20
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 20
          type: Utilization
