apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fhaa-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fhaa-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 30
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 30
          type: Utilization
