apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: fhaa-app
  name: fhaa-app
  namespace: fhaa
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: fhaa-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/junyjoy/Fhaha.git
      ref: loadtest
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-311:1-8.1686736783
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
